#!/usr/bin/env python3

template_engine = {
    "stamps/small-jp-en": {
        "template_prefix": "stamp",
        "template_file_names": ["horizontal", "vertical"],
        "template_field_names":         ["EN_LABEL",              "JP_LABEL"          ],
        "template_dataset": [
            ("arm-left",                ["LEFT ARM",              "左腕"              ]),
            ("arm-right",               ["RIGHT ARM",             "右腕"              ]),
            ("arm",                     ["ARM",                   "腕"                ]),
            ("assortment-match",        ["ASSORTMENT MATCH",      "組み合わせ"        ]),
            ("back-bl-mask",            ["BACK BL MASK",          "ウラBLヌリ"        ]),
            ("badge",                   ["BADGE",                 "バッチ"            ]),
            ("bag",                     ["BAG",                   "バッグ"            ]),
            ("balance-comp",            ["BALANCE COMP",          "他〜と合成"        ]),
            ("balance-do-t",            ["BALANCE DOⓉ",          "他〜を同トレス"    ]),
            ("balance-t",               ["BALANCEⓉ",             "他〜をトレス"      ]),
            ("balance",                 ["BALANCE",               "残りの部分"        ]),
            ("beard",                   ["BEARD",                 "髭"                ]),
            ("belt-buckle",             ["BELT BUCKLE",           "バックル"          ]),
            ("belt",                    ["BELT",                  "ベルト"            ]),
            ("bg-video",                ["BG VIDEO",              "環境映像"          ]),
            ("bl-efx-mask",             ["BL EFX MASK",           "透過光マスク"      ]),
            ("bl-efx",                  ["BL EFX",                "透過光"            ]),
            ("blink-action",            ["BLINK ACTION",          "中目パチ"          ]),
            ("blood",                   ["BLOOD",                 "血"                ]),
            ("blouse",                  ["BLOUSE",                "ブラウス"          ]),
            ("bluish-paint",            ["BLUISH PAINT",          "ブルートーン彩色"  ]),
            ("bottom-peg",              ["BOTTOM PEG",            "下タップ"          ]),
            ("brush-air",               ["AIR BRUSH",             "エアーブラシ"      ]),
            ("brush-dry",               ["DRY BRUSH",             "ドライブラシ"      ]),
            ("brush",                   ["BRUSH",                 "ブラシ"            ]),
            ("bure",                    ["BURE",                  "ブレ"              ]),
            ("button",                  ["BUTTON",                "バタン"            ]),
            ("catch-light",             ["CATCH LIGHT",           "キャッチライト"    ]),
            ("clear-mask",              ["CLEAR MASK",            "ヌキマスク"        ]),
            ("clear",                   ["CLEAR",                 "ヌキ"              ]),
            ("close-up",                ["CLOSE UP",              "クローズアップ"    ]),
            ("closed-eyes",             ["CLOSED EYES",           "閉目"              ]),
            ("closed-mouth",            ["CLOSED MOUTH",          "閉口"              ]),
            ("clothes-autumn",          ["AUTUMN",                "秋服"              ]),
            ("clothes-spring",          ["SPRING",                "春服"              ]),
            ("clothes-summer",          ["SUMMER",                "夏服"              ]),
            ("clothes-winter",          ["WINTER",                "冬服"              ]),
            ("clothes",                 ["CLOTHES",               "服"                ]),
            ("cloud",                   ["CLOUD",                 "雲"                ]),
            ("coat",                    ["COAT",                  "コート"            ]),
            ("collar",                  ["COLLAR",                "カラー"            ]),
            ("color-ht",                ["COLOR H.Ⓣ",            "色トレス"          ]),
            ("com-ng",                  ["COM. NG",               "合成不可"          ]),
            ("come-in-this",            ["COME IN THIS",          "これでIN"          ]),
            ("compound",                ["COMPOUND",              "合成"              ]),
            ("costume",                 ["COSTUME",               "コスチューム"      ]),
            ("counter-light",           ["COUNTER LIGHT",         "逆光"              ]),
            ("crotch-line",             ["CROTCH LINE",           "股下ライン"        ]),
            ("cut-back",                ["CUT BACK",              "カットバック"      ]),
            ("cut-in",                  ["CUT IN",                "カットイン"        ]),
            ("cut-insert",              ["INSERT CUT",            "インサートカット"  ]),
            ("cut",                     ["CUT",                   "カット"            ]),
            ("day",                     ["DAY",                   "昼"                ]),
            ("dial-com",                ["DIAL.COM",              "セリフ合成"        ]),
            ("disuse-shadow",           ["DISUSE SHADOW",         "カゲ不要"          ]),
            ("earring",                 ["EARRING",               "イヤリング"        ]),
            ("evening-color",           ["EVENING COLOR",         "夕景彩色"          ]),
            ("expression",              ["EXPRESSION",            "表情"              ]),
            ("eye",                     ["EYE",                   "目"                ]),
            ("eyebrow",                 ["EYEBROW",               "眉"                ]),
            ("eyeshadow",               ["EYESHADOW",             "アイシャドー"      ]),
            ("fade-in",                 ["FADE IN",               "フェードイン"      ]),
            ("fade-out",                ["FADE OUT",              "フェードアウト"    ]),
            ("fill-light",              ["FILL LIGHT",            "補助光"            ]),
            ("finger",                  ["FINGER",                "ゆび"              ]),
            ("fire",                    ["FIRE",                  "火"                ]),
            ("focus-in",                ["FOCUS IN",              "フォークスイン"    ]),
            ("focus-out",               ["FOCUS OUT",             "フォークスアウト"  ]),
            ("focus",                   ["FOCUS",                 "フォークス"        ]),
            ("follow",                  ["FOLLOW",                "フォロー"          ]),
            ("foot-left",               ["LEFT FOOT",             "左足"              ]),
            ("foot-right",              ["RIGHT FOOT",            "右足"              ]),
            ("foot",                    ["FOOT",                  "足"                ]),
            ("forest",                  ["FOREST",                "森"                ]),
            ("frame-in",                ["FRAME IN",              "フレームイン"      ]),
            ("frame-out",               ["FRAME OUT",             "フレームアウト"    ]),
            ("frame",                   ["FRAME",                 "フレーム"          ]),
            ("free-coloring",           ["FREE COLORING",         "自由彩色"          ]),
            ("frills",                  ["FRILLS",                "フリル"            ]),
            ("gensatsu-finished",       ["GENSATSU FINISHED",     "原撮済"            ]),
            ("glasses",                 ["GLASSES",               "ガラス"            ]),
            ("gloves",                  ["GLOVES",                "手袋"              ]),
            ("grayscale",               ["GRAYSCALE",             "グレースケール"    ]),
            ("ground-shadow",           ["GROUND SHADOW",         "地面の影"          ]),
            ("guest-character",         ["GUEST CHARACTER",       "ゲストキャラクター"]),
            ("hair",                    ["HAIR",                  "髪"                ]),
            ("half-open-eye",           ["HALF OPEN EYE",         "半分開き目"        ]),
            ("hand-left",               ["LEFT HAND",             "左手"              ]),
            ("hand-right",              ["RIGHT HAND",            "右手"              ]),
            ("hand",                    ["HAND",                  "手"                ]),
            ("hat",                     ["HAT",                   "帽子"              ]),
            ("held",                    ["HELD",                  "止め"              ]),
            ("high-contrast",           ["HIGH CONTRAST",         "ハイコントラスト"  ]),
            ("in-between",              ["IN-BETWEEN",            "動画"              ]),
            ("iris",                    ["IRIS",                  "虹彩"              ]),
            ("jacket",                  ["JACKET",                "ジャケット"        ]),
            ("jaw-line",                ["JAW LINE",              "顎ライン"          ]),
            ("jeans",                   ["JEANS",                 "ジーンズ"          ]),
            ("kakikomi",                ["KAKIKOMI",              "〜に描き込み"      ]),
            ("key-animation",           ["KEY ANIMATION",         "原画"              ]),
            ("key-light",               ["KEY LIGHT",             "主光線"            ]),
            ("kneesocks",               ["KNEESOCKS",             "ニーソックス"      ]),
            ("large-cel",               ["LARGE CEL",             "大判セル"          ]),
            ("layer",                   ["LAYER",                 "レイヤー"          ]),
            ("layout",                  ["LAYOUT",                "レイアウト"        ]),
            ("leg-left",                ["LEFT LEG",              "左脚"              ]),
            ("leg-right",               ["RIGHT LEG",             "右脚"              ]),
            ("leg",                     ["LEG",                   "脚"                ]),
            ("lettering",               ["LETTERING",             "レタリング"        ]),
            ("light",                   ["LIGHT",                 "光"                ]),
            ("line-light",              ["LINE LIGHT",            "ラインライト"      ]),
            ("lip-synch",               ["LIP SYNCH",             "セリフ"            ]),
            ("lipstick",                ["LIPSTICK",              "口紅"              ]),
            ("long-cel",                ["LONG CEL",              "長セル"            ]),
            ("loop",                    ["LOOP",                  "ループ"            ]),
            ("lower-lip",               ["LOWER LIP",             "下唇"              ]),
            ("ls-action",               ["L.S. ACTION",           "中割り口パク"      ]),
            ("ls-covers",               ["L.S. COVERS",           "セリフかぶせ"      ]),
            ("main-character",          ["MAIN CHARACTER",        "マインキャラクター"]),
            ("main-light",              ["MAIN LIGHT",            "マインライト"      ]),
            ("man",                     ["MAN",                   "男"                ]),
            ("mask-female",             ["FEMALE MASK",           "メスマスク"        ]),
            ("mask-male",               ["MALE MASK",             "オスマスク"        ]),
            ("match-color-with",        ["MATCH COLOR WITH 〜",   "〜と色合わせ"      ]),
            ("middle-eyes",             ["MIDDLE EYES",           "中目"              ]),
            ("middle-mouth",            ["MIDDLE MOUTH",          "中口"              ]),
            ("monochrome",              ["MONOCHROME",            "モノクローム"      ]),
            ("monotone",                ["MONOTONE",              "モノトーン"        ]),
            ("mouth",                   ["MOUTH",                 "口の中"            ]),
            ("nail",                    ["NAIL",                  "爪"                ]),
            ("neck",                    ["NECK",                  "首"                ]),
            ("necklace",                ["NECKLACE",              "ネックレス"        ]),
            ("necktie",                 ["NECKTIE",               "ネクタイ"          ]),
            ("night",                   ["NIGHT",                 "夜色"              ]),
            ("no-need",                 ["NO NEED",               "不要"              ]),
            ("no-shadow-for-balance",   ["NO SHADOW FOR BALANCE", "他影不要"          ]),
            ("none",                    ["NONE",                  "なし"              ]),
            ("normal-color-1",          ["NORMAL COLOR",          "ノーマル"          ]),
            ("normal-color-2",          ["NORMAL COLOR",          "ノーマルカラー"    ]),
            ("normal",                  ["NORMAL",                "ノーマル"          ]),
            ("off-scene",               ["OFF SCENE",             "オフシーン"        ]),
            ("one-tone-darker-1",       ["1 TONE DARKER",         "ノーマル段カゲ"    ]),
            ("one-tone-darker-2",       ["1 TONE DARKER",         "影１段落とし"      ]),
            ("one-tone-lighter",        ["1 TONE LIGHTER",        "ノーマル一段上げ"  ]),
            ("open-eye",                ["OPEN EYE",              "開きめ"            ]),
            ("open-mouth",              ["OPEN MOUTH",            "開け口"            ]),
            ("overlap",                 ["OVERLAP",               "オーバーラップ"    ]),
            ("overlay",                 ["OVERLAY",               "BOOK上"            ]),
            ("p-to-edge",               ["Ⓟ TO EDGE",            "セルバレ注意"      ]),
            ("p-whole-frame",           ["Ⓟ WHOLE FRAME",        "全面塗り"          ]),
            ("paint_1",                 ["Ⓟ",                    "ペイント"          ]),
            ("paint_2",                 ["PAINT",                 "ペイント"          ]),
            ("pan-focus",               ["PAN-FOCUS",             "パンフォークス"    ]),
            ("parallax",                ["PARALLAX",              "パララックス"      ]),
            ("preview",                 ["PREVIEW",               "プレビュー"        ]),
            ("pupil",                   ["PUPIL",                 "瞳"                ]),
            ("rain",                    ["RAIN",                  "雨"                ]),
            ("reference",               ["REFERENCE",             "参考"              ]),
            ("reg-to",                  ["REG. TO",               "〜と組合せ"        ]),
            ("repeat",                  ["REPEAT",                "リピート"          ]),
            ("reverse-use",             ["REVERSE USE",           "逆シート"          ]),
            ("ribbon",                  ["RIBBON",                "リボン"            ]),
            ("rotoscope",               ["ROTOSCOPE",             "ロトスコープ"      ]),
            ("scarf",                   ["SCARF",                 "スカーフ"          ]),
            ("scene",                   ["SCENE",                 "シーン"            ]),
            ("separate-cel",            ["SEPARATE CEL",          "別セル"            ]),
            ("shadow-1",                ["SHADOW",                "カゲ"              ]),
            ("shadow-2",                ["SHADOW",                "カゲ有り"          ]),
            ("shadow-for-only",         ["SHADOW FOR ONLY 〜",    "〜のみ影あり"      ]),
            ("shadow-one",              ["SHADOW 1",              "一号影"            ]),
            ("shadow-three-darker",     ["SHADOW 3 DARKER",       "影３段落とし"      ]),
            ("shadow-two-darker",       ["SHADOW 2 DARKER",       "影２段落とし"      ]),
            ("shadow-two",              ["SHADOW 2",              "二号影"            ]),
            ("shirt",                   ["SHIRT",                 "シャツ"            ]),
            ("shoe-sole",               ["SHOE SOLE",             "靴裏"              ]),
            ("shoe",                    ["SHOE",                  "靴"                ]),
            ("shoulder-left",           ["LEFT SHOULDER",         "左肩"              ]),
            ("shoulder-right",          ["RIGHT SHOULDER",        "右肩"              ]),
            ("shoulder",                ["SHOULDER",              "肩"                ]),
            ("silhouette",              ["SILHOUETTE",            "シルエット"        ]),
            ("skin",                    ["SKIN",                  "肌"                ]),
            ("skirt",                   ["SKIRT",                 "スカート"          ]),
            ("sky-blue",                ["BLUE SKY",              "青空"              ]),
            ("sky-evening",             ["EVENING SKY",           "夕空"              ]),
            ("sky-morning",             ["MORNING SKY",           "朝空"              ]),
            ("sky-night",               ["NIGHT SKY",             "夜空"              ]),
            ("sky-rainy",               ["RAINY SKY",             "雨空"              ]),
            ("sky-starry",              ["STARRY SKY",            "星空"              ]),
            ("sky",                     ["SKY",                   "空"                ]),
            ("slide",                   ["SLIDE",                 "スライド"          ]),
            ("smoke",                   ["SMOKE",                 "煙"                ]),
            ("socks-1",                 ["SOCKS",                 "靴下"              ]),
            ("socks-2",                 ["SOCKS",                 "くつした"          ]),
            ("stage-left",              ["STAGE LEFT",            "上手"              ]),
            ("stage-right",             ["STAGE RIGHT",           "下手"              ]),
            ("steam",                   ["STEAM",                 "湯気"              ]),
            ("stocking",                ["STOCKING",              "ストッキング"      ]),
            ("strobe-fx",               ["STROBE FX",             "ストロボ効果"      ]),
            ("suit",                    ["SUIT",                  "スーツ"            ]),
            ("sweat",                   ["SWEAT",                 "汗"                ]),
            ("swimsuit",                ["SWIMSUIT",              "水着"              ]),
            ("symmetry",                ["SYMMETRY",              "シンメトリー"      ]),
            ("tears",                   ["TEARS",                 "涙"                ]),
            ("teeth",                   ["TEETH",                 "歯"                ]),
            ("tilt",                    ["TILT",                  "チルト"            ]),
            ("time-sheet",              ["TIME SHEET",            "タイムシート"      ]),
            ("tojikuchi-k",             ["TOJIKUCHI K.",          "閉じ口描き込み"    ]),
            ("tongue",                  ["TONGUE",                "舌"                ]),
            ("top-and-bottom-peg",      ["TOP&BOTTOM PEG",        "上下タップ"        ]),
            ("top-light",               ["TOP LIGHT",             "トップライト"      ]),
            ("top-peg",                 ["TOP PEG",               "上タップ"          ]),
            ("touch",                   ["TOUCH",                 "タッチ"            ]),
            ("trace_1",                 ["Ⓣ",                    "トレス"            ]),
            ("trace_2",                 ["TRACE",                 "トレス"            ]),
            ("tree",                    ["TREE",                  "木"                ]),
            ("underlay",                ["UNDERLAY",              "BOOK下"            ]),
            ("underwear",               ["UNDERWEAR",             "パンツ"            ]),
            ("uniform-1",               ["UNIFORM",               "ユニフォーム"      ]),
            ("uniform-2",               ["UNIFORM",               "校服"              ]),
            ("up-and-down-action",      ["UP/DOWN ACTION",        "(動きに)山をつける"]),
            ("upper-lip",               ["UPPER LIP",             "上唇"              ]),
            ("wall",                    ["WALL",                  "かべ"              ]),
            ("water",                   ["WATER",                 "水"                ]),
            ("white-of-eye",            ["WHITE OF EYE",          "白目"              ]),
            ("wings",                   ["WINGS",                 "翼"                ]),
            ("wipe-in",                 ["WIPE IN",               "ワイプイン"        ]),
            ("wipe-out",                ["WIPE OUT",              "ワイプアウト"      ]),
            ("woman",                   ["WOMAN",                 "女"                ]),
        ],
    },
    "stamps/large-jp": {
        "template_prefix": "stamp",
        "template_file_names": ["horizontal", "vertical"],
        "template_field_names":                   ["JP_LABEL",     "576"],
        "template_dataset": [
            ("clean-copy",                        ["清書",         "110"]),
            ("color-design",                      ["色彩設計",     "210"]),
            ("comparison",                        ["对比",         "110"]),
            ("confidential",                      ["社外秘",       "160"]),
            ("douga-collection",                  ["動画集",       "160"]),
            ("draft-final",                       ["決定稿",       "160"]),
            ("draft-preliminary",                 ["準備稿",       "160"]),
            ("gensatsu-finished",                 ["原撮済",       "160"]),
            ("keyframe-1",                        ["原画",         "110"]),
            ("layout-1",                          ["レイアウト",   "250"]),
            ("layout-2",                          ["原図",         "110"]),
            ("page-x",                            ["PAGE　　",     "200"]),
            ("prohibited-reproduction",           ["無断転載禁止", "310"]),
            ("reference",                         ["参考",         "110"]),
            ("revision-animation-director",       ["作監修正",     "210"]),
            ("revision-chief-animation-director", ["総作監修正",   "260"]),
            ("revision-episode-director",         ["演出修正",     "210"]),
            ("revision-series-director",          ["監督修正",     "210"]),
            ("revision",                          ["修正",         "110"]),
            ("scan-required",                     ["要SCAN",       "190"]),
            ("submitted",                         ["原図出済",     "210"]),
        ],
    }
}

for (template_base_directory, template) in template_engine.items():
    for template_file_name in template["template_file_names"]:
        template_svg_path = "{}/.templates/template-{}.svg".format(
            template_base_directory,
            template_file_name,
        )

        with open(template_svg_path, "r") as template_svg_file:
            template_svg_data = template_svg_file.read()

        for (instance_name, instance_data) in template["template_dataset"]:
            instance_svg_data = template_svg_data
            for (a, b) in zip(template["template_field_names"], instance_data):
                instance_svg_data = instance_svg_data.replace(a, b.replace("&", "&amp;"))

            instance_svg_path = "{}/{}/{}-{}.svg".format(
                template_base_directory,
                template_file_name,
                template["template_prefix"],
                instance_name
            )

            with open(instance_svg_path, "w") as instance_svg_file:
                instance_svg_file.write(instance_svg_data)
