#!/usr/bin/env python3

template_engine = {
    "stamps/small-jp-en": {
        "template_prefix": "stamp",
        "template_file_names": ["horizontal", "vertical"],
        "template_field_names":         ["EN_LABEL",              "JP_LABEL"          ],
        "template_dataset": [
            ("back-bl-mask",            ["BACK BL MASK",          "ウラBLヌリ"        ]),
            ("badge",                   ["BADGE",                 "バッチ"            ]),
            ("bag",                     ["BAG",                   "バッグ"            ]),
            ("balance-comp",            ["BALANCE COMP",          "他〜と合成"        ]),
            ("balance-do-t",            ["BALANCE DOⓉ",          "他〜を同トレス"    ]),
            ("balance-t",               ["BALANCEⓉ",             "他〜をトレス"      ]),
            ("balance",                 ["BALANCE",               "残りの部分"        ]),
            ("beard",                   ["BEARD",                 "髭"                ]),
            ("belt-buckle",             ["BELT BUCKLE",           "バックル"          ]),
            ("belt",                    ["BELT",                  "ベルト"            ]),
            ("bl-efx-mask",             ["BL EFX MASK",           "透過光マスク"      ]),
            ("bl-efx",                  ["BL EFX",                "透過光"            ]),
            ("blink-action",            ["BLINK ACTION",          "中目パチ"          ]),
            ("blood",                   ["BLOOD",                 "血"                ]),
            ("blouse",                  ["BLOUSE",                "ブラウス"          ]),
            ("brush",                   ["BRUSH",                 "ブラシ"            ]),
            ("bure",                    ["BURE",                  "ブレ"              ]),
            ("button",                  ["BUTTON",                "バタン"            ]),
            ("clear-mask",              ["CLEAR MASK",            "ヌキマスク"        ]),
            ("clear",                   ["CLEAR",                 "ヌキ"              ]),
            ("closed-eyes",             ["CLOSED EYES",           "閉目"              ]),
            ("closed-mouth",            ["CLOSED MOUTH",          "閉口"              ]),
            ("clothes-autumn",          ["AUTUMN",                "秋服"              ]),
            ("clothes-spring",          ["SPRING",                "春服"              ]),
            ("clothes-summer",          ["SUMMER",                "夏服"              ]),
            ("clothes-winter",          ["WINTER",                "冬服"              ]),
            ("clothes",                 ["CLOTHES",               "服"                ]),
            ("coat",                    ["COAT",                  "コート"            ]),
            ("collar",                  ["COLLAR",                "カラー"            ]),
            ("compound",                ["COMPOUND",              "合成"              ]),
            ("costume",                 ["COSTUME",               "コスチューム"      ]),
            ("crotch-line",             ["CROTCH LINE",           "股下ライン"        ]),
            ("dial-com",                ["DIAL.COM",              "セリフ合成"        ]),
            ("disuse-shadow",           ["DISUSE SHADOW",         "カゲ不要"          ]),
            ("earring",                 ["EARRING",               "イヤリング"        ]),
            ("evening-color",           ["EVENING COLOR",         "夕景彩色"          ]),
            ("eye",                     ["EYE",                   "目"                ]),
            ("eyebrow",                 ["EYEBROW",               "眉"                ]),
            ("eyeshadow",               ["EYESHADOW",             "アイシャドー"      ]),
            ("finger",                  ["FINGER",                "ゆび"              ]),
            ("forest",                  ["FOREST",                "森"                ]),
            ("frame",                   ["FRAME",                 "フレーム"          ]),
            ("free-coloring",           ["FREE COLORING",         "自由彩色"          ]),
            ("frills",                  ["FRILLS",                "フリル"            ]),
            ("glasses",                 ["GLASSES",               "ガラス"            ]),
            ("gloves",                  ["GLOVES",                "手袋"              ]),
            ("ground-shadow",           ["GROUND SHADOW",         "地面の影"          ]),
            ("guest-character",         ["GUEST CHARACTER",       "ゲストキャラクター"]),
            ("hair",                    ["HAIR",                  "髪"                ]),
            ("half-open-eye",           ["HALF OPEN EYE",         "半分開き目"        ]),
            ("hat",                     ["HAT",                   "帽子"              ]),
            ("held",                    ["HELD",                  "止め"              ]),
            ("high-contrast",           ["HIGH CONTRAST",         "ハイコントラスト"  ]),
            ("iris",                    ["IRIS",                  "虹彩"              ]),
            ("jacket",                  ["JACKET",                "ジャケット"        ]),
            ("jaw-line",                ["JAW LINE",              "顎ライン"          ]),
            ("jeans",                   ["JEANS",                 "ジーンズ"          ]),
            ("kakikomi",                ["KAKIKOMI",              "〜に描き込み"      ]),
            ("kneesocks",               ["KNEESOCKS",             "ニーソックス"      ]),
            ("large-cel",               ["LARGE CEL",             "大判セル"          ]),
            ("light",                   ["LIGHT",                 "光"                ]),
            ("lip-synch",               ["LIP SYNCH",             "セリフ"            ]),
            ("lipstick",                ["LIPSTICK",              "口紅"              ]),
            ("long-cel",                ["LONG CEL",              "長セル"            ]),
            ("lower-lip",               ["LOWER LIP",             "下唇"              ]),
            ("ls-action",               ["L.S. ACTION",           "中割り口パク"      ]),
            ("ls-covers",               ["L.S. COVERS",           "セリフかぶせ"      ]),
            ("main-character",          ["MAIN CHARACTER",        "マインキャラクター"]),
            ("man",                     ["MAN",                   "男"                ]),
            ("middle-eyes",             ["MIDDLE EYES",           "中目"              ]),
            ("middle-mouth",            ["MIDDLE MOUTH",          "中口"              ]),
            ("mouth",                   ["MOUTH",                 "口の中"            ]),
            ("nail",                    ["NAIL",                  "爪"                ]),
            ("necklace",                ["NECKLACE",              "ネックレス"        ]),
            ("necktie",                 ["NECKTIE",               "ネクタイ"          ]),
            ("night",                   ["NIGHT",                 "夜色"              ]),
            ("no-need",                 ["NO NEED",               "不要"              ]),
            ("no-shadow-for-balance",   ["NO SHADOW FOR BALANCE", "他影不要"          ]),
            ("none",                    ["NONE",                  "なし"              ]),
            ("normal-color-1",          ["NORMAL COLOR",          "ノーマル"          ]),
            ("normal-color-2",          ["NORMAL COLOR",          "ノーマルカラー"    ]),
            ("normal",                  ["NORMAL",                "ノーマル"          ]),
            ("one-tone-darker-1",       ["1 TONE DARKER",         "ノーマル段カゲ"    ]),
            ("one-tone-darker-2",       ["1 TONE DARKER",         "影１段落とし"      ]),
            ("one-tone-lighter",        ["1 TONE LIGHTER",        "ノーマル一段上げ"  ]),
            ("open-eye",                ["OPEN EYE",              "開きめ"            ]),
            ("open-mouth",              ["OPEN MOUTH",            "開け口"            ]),
            ("p-to-edge",               ["Ⓟ TO EDGE",            "セルバレ注意"      ]),
            ("paint_1",                 ["Ⓟ",                    "ペイント"          ]),
            ("paint_2",                 ["PAINT",                 "ペイント"          ]),
            ("pupil",                   ["PUPIL",                 "瞳"                ]),
            ("rain",                    ["RAIN",                  "雨"                ]),
            ("reference",               ["REFERENCE",             "参考"              ]),
            ("reg-to",                  ["REG. TO",               "〜と組合せ"        ]),
            ("ribbon",                  ["RIBBON",                "リボン"            ]),
            ("scarf",                   ["SCARF",                 "スカーフ"          ]),
            ("separate-cel",            ["SEPARATE CEL",          "別セル"            ]),
            ("shadow-1",                ["SHADOW",                "カゲ"              ]),
            ("shadow-2",                ["SHADOW",                "カゲ有り"          ]),
            ("shadow-for-only",         ["SHADOW FOR ONLY 〜",    "〜のみ影あり"      ]),
            ("shadow-one",              ["SHADOW 1",              "一号影"            ]),
            ("shadow-three-darker",     ["SHADOW 3 DARKER",       "影３段落とし"      ]),
            ("shadow-two-darker",       ["SHADOW 2 DARKER",       "影２段落とし"      ]),
            ("shadow-two",              ["SHADOW 2",              "二号影"            ]),
            ("shirt",                   ["SHIRT",                 "シャツ"            ]),
            ("shoe-sole",               ["SHOE SOLE",             "靴裏"              ]),
            ("shoe",                    ["SHOE",                  "靴"                ]),
            ("shoulder",                ["SHOULDER",              "肩"                ]),
            ("silhouette",              ["SILHOUETTE",            "シルエット"        ]),
            ("skin",                    ["SKIN",                  "肌"                ]),
            ("skirt",                   ["SKIRT",                 "スカート"          ]),
            ("sky-blue",                ["BLUE SKY",              "青空"              ]),
            ("sky-evening",             ["EVENING SKY",           "夕空"              ]),
            ("sky-morning",             ["MORNING SKY",           "朝空"              ]),
            ("sky-night",               ["NIGHT SKY",             "夜空"              ]),
            ("sky-rainy",               ["RAINY SKY",             "雨空"              ]),
            ("sky-starry",              ["STARRY SKY",            "星空"              ]),
            ("sky",                     ["SKY",                   "空"                ]),
            ("slide",                   ["SLIDE",                 "スライド"          ]),
            ("socks-1",                 ["SOCKS",                 "靴下"              ]),
            ("socks-2",                 ["SOCKS",                 "くつした"          ]),
            ("stocking",                ["STOCKING",              "ストッキング"      ]),
            ("suit",                    ["SUIT",                  "スーツ"            ]),
            ("sweat",                   ["SWEAT",                 "汗"                ]),
            ("swimsuit",                ["SWIMSUIT",              "水着"              ]),
            ("tears",                   ["TEARS",                 "涙"                ]),
            ("teeth",                   ["TEETH",                 "歯"                ]),
            ("tojikuchi-k",             ["TOJIKUCHI K.",          "閉じ口描き込み"    ]),
            ("tongue",                  ["TONGUE",                "舌"                ]),
            ("top-and-bottom-peg",      ["TOP&BOTTOM PEG",        "上下タップ"        ]),
            ("touch",                   ["TOUCH",                 "タッチ"            ]),
            ("trace_1",                 ["Ⓣ",                    "トレス"            ]),
            ("trace_2",                 ["TRACE",                 "トレス"            ]),
            ("underwear",               ["UNDERWEAR",             "パンツ"            ]),
            ("uniform-1",               ["UNIFORM",               "ユニフォーム"      ]),
            ("uniform-2",               ["UNIFORM",               "校服"              ]),
            ("up-and-down-action",      ["UP/DOWN ACTION",        "(動きに)山をつける"]),
            ("upper-lip",               ["UPPER LIP",             "上唇"              ]),
            ("white-of-eye",            ["WHITE OF EYE",          "白目"              ]),
            ("woman",                   ["WOMAN",                 "女"                ]),
        ],
    },
    "stamps/large-jp": {
        "template_prefix": "stamp",
        "template_file_names": ["horizontal", "vertical"],
        "template_field_names":                   ["JP_LABEL",     "576"],
        "template_dataset": [
            ("clean-copy",                        ["清書",         "110"]),
            ("color-design",                      ["色彩設計",     "210"]),
            ("comparison",                        ["对比",         "110"]),
            ("confidential",                      ["社外秘",       "160"]),
            ("douga-collection",                  ["動画集",       "160"]),
            ("draft-final",                       ["決定稿",       "160"]),
            ("draft-preliminary",                 ["準備稿",       "160"]),
            ("keyframe-1",                        ["原画",         "110"]),
            ("layout-1",                          ["レイアウト",   "250"]),
            ("layout-2",                          ["原図",         "110"]),
            ("page-x",                            ["PAGE　　",     "200"]),
            ("prohibited-reproduction",           ["無断転載禁止", "310"]),
            ("reference",                         ["参考",         "110"]),
            ("revision-animation-director",       ["作監修正",     "210"]),
            ("revision-chief-animation-director", ["総作監修正",   "260"]),
            ("revision-episode-director",         ["演出修正",     "210"]),
            ("revision-series-director",          ["監督修正",     "210"]),
            ("revision",                          ["修正",         "110"]),
            ("scan-required",                     ["要SCAN",       "190"]),
            ("submitted",                         ["原図出済",     "210"]),
        ],
    }
}

for (template_base_directory, template) in template_engine.items():
    for template_file_name in template["template_file_names"]:
        template_svg_path = "{}/.templates/template-{}.svg".format(
            template_base_directory,
            template_file_name,
        )

        with open(template_svg_path, "r") as template_svg_file:
            template_svg_data = template_svg_file.read()

        for (instance_name, instance_data) in template["template_dataset"]:
            instance_svg_data = template_svg_data
            for (a, b) in zip(template["template_field_names"], instance_data):
                instance_svg_data = instance_svg_data.replace(a, b.replace("&", "&amp;"))

            instance_svg_path = "{}/{}/{}-{}.svg".format(
                template_base_directory,
                template_file_name,
                template["template_prefix"],
                instance_name
            )

            with open(instance_svg_path, "w") as instance_svg_file:
                instance_svg_file.write(instance_svg_data)
